Repository replicatedhq/sbctl, pull requests merged in 2024-08, with the labels that each got.

#172 Print extracted bundle path
  cli/serve.go
  cli/shell.go
Labels: type::chore

#173 chore: Update readme
  README.md
Labels: type::chore

#176 feat: flag to cd to support bundle dir on starting shell
  cli/shell.go
Labels: type::feature

#179 fix: remove gorelease prerelease flag
  deploy/.goreleaser.yaml
Labels: bug::normal, type::bug
