Repository replicatedhq/sbctl, pull requests merged in 2024-10, with the labels that each got.

#187 feat: download and extract bundles that do not have cluster resources using shell subcommand
  cli/download.go
  cli/serve.go
  cli/shell.go
Labels: type::feature

#189 bug: kubectl describe node does not apply node filter on pod list
  pkg/api/server.go
Labels: bug::normal

#192 Format statefulset table output
  pkg/api/server.go
Labels: type::chore
