Repository replicatedhq/sbctl, pull requests merged in 2024-12, with the labels that each got.

#198 add auto merge for Dependabot PRs
  .github/workflows/automated-prs-manager.yaml
  .github/workflows/build-checks.yaml
Labels: type::chore

#203 fix(dependabot): fix auto merge fail
  .github/dependabot.yml
  .github/workflows/build-checks.yaml
  .github/workflows/release.yaml
  go.mod
Labels: bug::normal, type::bug

#206 fix: go mod resolve 0.0.0 version
  .github/dependabot.yml
  go.mod
  go.sum
Labels: bug::normal, type::bug, type::security

#208 fix: add missing build checks
  .github/workflows/automated-prs-manager.yaml
  .github/workflows/build-checks.yaml
Labels: bug::normal, type::bug
